### ISSUE TITLE
Intellij 2020.3 EAP compatibility

### ISSUE THREAD

**Issue by doublefx** [chrisly42/cajon-plugin#2]
Hi,

Getting this issue with the last EAP and had to disabled the plugin:

Following exceptions happened soon after this one, most probably they are induced.

2020-10-02T12:39:16.863
com.intellij.diagnostic.PluginException: Could not initialize class de.platon42.intellij.plugins.cajon.inspections.ImplicitAssertionInspection [Plugin: de.platon42.cajon]
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateExtensionWithPicoContainerOnlyIfNeeded(ComponentManagerImpl.kt:678)
	at com.intellij.serviceContainer.LazyExtensionInstance.createInstance(LazyExtensionInstance.java:43)
	at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.createInstance(CustomLoadingExtensionPointBean.java:29)
	at com.intellij.codeInspection.InspectionEP.instantiateTool(InspectionEP.java:206)
	at com.intellij.codeInspection.ex.InspectionToolWrapper.getTool(InspectionToolWrapper.java:76)
	at com.intellij.codeInspection.ex.InspectionToolWrapper.getDisplayName(InspectionToolWrapper.java:151)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.addTool(InspectionProfileImpl.java:553)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.initialize(InspectionProfileImpl.java:474)
	at com.intellij.codeInspection.ex.NewInspectionProfile.initInspectionTools(InspectionProfile.kt:112)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.initialize(InspectionProfileImpl.java:461)
	at com.intellij.codeInspection.ex.NewInspectionProfile.initInspectionTools(InspectionProfile.kt:112)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.getToolsOrNull(InspectionProfileImpl.java:881)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.getInspectionTool(InspectionProfileImpl.java:295)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.getUnwrappedTool(InspectionProfileImpl.java:301)
	at com.intellij.xml.util.HtmlUtil.getEntitiesString(HtmlUtil.java:319)
	at com.intellij.xml.util.HtmlUtil.getCustomTagDescriptors(HtmlUtil.java:296)
	at org.intellij.html.RelaxedHtmlFromRngNSDescriptor.getRootElementsDescriptors(RelaxedHtmlFromRngNSDescriptor.java:74)
	at com.intellij.psi.impl.source.xml.XmlDocumentImpl.getNSDescriptorFromMetaData(XmlDocumentImpl.java:341)
	at com.intellij.psi.impl.source.xml.XmlDocumentImpl.getNsDescriptorFormDocType(XmlDocumentImpl.java:319)
	at com.intellij.psi.impl.source.xml.XmlDocumentImpl.getDefaultNSDescriptorInner(XmlDocumentImpl.java:198)
	at com.intellij.psi.impl.source.xml.XmlDocumentImpl.lambda$getDefaultNSDescriptor$0(XmlDocumentImpl.java:164)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:235)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:236)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.psi.impl.source.xml.XmlDocumentImpl.getDefaultNSDescriptor(XmlDocumentImpl.java:175)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getNSDescriptor(XmlTagDelegate.java:227)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getNSDescriptor(XmlTagImpl.java:100)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getNSDescriptor(XmlTagDelegate.java:230)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getNSDescriptor(XmlTagImpl.java:100)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getNSDescriptor(XmlTagDelegate.java:230)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getNSDescriptor(XmlTagImpl.java:100)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getNSDescriptor(XmlTagDelegate.java:230)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getNSDescriptor(XmlTagImpl.java:100)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getNSDescriptor(XmlTagDelegate.java:230)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getNSDescriptor(XmlTagImpl.java:100)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getNSDescriptor(XmlTagDelegate.java:230)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getNSDescriptor(XmlTagImpl.java:100)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getNSDescriptor(XmlTagDelegate.java:230)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getNSDescriptor(XmlTagImpl.java:100)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getNSDescriptor(XmlTagDelegate.java:230)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getNSDescriptor(XmlTagImpl.java:100)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getNSDescriptor(XmlTagDelegate.java:230)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getNSDescriptor(XmlTagImpl.java:100)
	at com.intellij.xml.util.XmlUtil.isTagDefinedByNamespace(XmlUtil.java:1235)
	at org.angularjs.codeInsight.tags.AngularJSTagDescriptorsProvider.getDescriptor(AngularJSTagDescriptorsProvider.java:60)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.computeElementDescriptor(XmlTagDelegate.java:457)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate$1.compute(XmlTagDelegate.java:436)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:153)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:235)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:236)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:76)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:150)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:120)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getDescriptor(XmlTagDelegate.java:432)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getDescriptor(XmlTagImpl.java:129)
	at com.intellij.xml.util.XmlEnumeratedValueReferenceProvider$1.getDescriptor(XmlEnumeratedValueReferenceProvider.java:93)
	at com.intellij.xml.util.XmlEnumeratedValueReferenceProvider$1.getDescriptor(XmlEnumeratedValueReferenceProvider.java:89)
	at com.intellij.xml.util.XmlEnumeratedValueReferenceProvider.getReferencesByElement(XmlEnumeratedValueReferenceProvider.java:63)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:204)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:167)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:146)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:44)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getReferencesImpl(XmlTagDelegate.java:161)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getDefaultReferences(XmlTagDelegate.java:127)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getReferences(XmlTagImpl.java:95)
	at com.intellij.psi.PsiReferenceServiceImpl.doGetReferences(PsiReferenceServiceImpl.java:35)
	at com.intellij.psi.PsiReferenceServiceImpl.getReferences(PsiReferenceServiceImpl.java:24)
	at com.intellij.psi.search.SingleTargetRequestResultProcessor.processTextOccurrence(SingleTargetRequestResultProcessor.java:32)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$5.lambda$execute$0(PsiSearchHelperImpl.java:948)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTreeUp(LowLevelSearchUtil.java:87)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.lambda$processElementsAtOffsets$0(LowLevelSearchUtil.java:178)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processOffsets(LowLevelSearchUtil.java:204)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsAtOffsets(LowLevelSearchUtil.java:177)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$5.execute(PsiSearchHelperImpl.java:944)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:280)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:271)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:25)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:885)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:25)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processCandidates$18(PsiSearchHelperImpl.java:905)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processVirtualFile$11(PsiSearchHelperImpl.java:543)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1132)
	at com.intellij.openapi.application.ex.ApplicationUtil.tryRunReadAction(ApplicationUtil.java:33)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processVirtualFile(PsiSearchHelperImpl.java:525)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processPsiFileRoots$7(PsiSearchHelperImpl.java:400)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processFilesConcurrentlyDespiteWriteActions$8(PsiSearchHelperImpl.java:473)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processFilesConcurrentlyDespiteWriteActions$9(PsiSearchHelperImpl.java:472)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class de.platon42.intellij.plugins.cajon.inspections.ImplicitAssertionInspection
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateExtensionWithPicoContainerOnlyIfNeeded(ComponentManagerImpl.kt:675)
	... 123 more

2020-10-02T12:39:16.864
com.intellij.diagnostic.PluginException: Could not initialize class de.platon42.intellij.plugins.cajon.inspections.ImplicitAssertionInspection [Plugin: de.platon42.cajon]
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateExtensionWithPicoContainerOnlyIfNeeded(ComponentManagerImpl.kt:678)
	at com.intellij.serviceContainer.LazyExtensionInstance.createInstance(LazyExtensionInstance.java:43)
	at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.createInstance(CustomLoadingExtensionPointBean.java:29)
	at com.intellij.codeInspection.InspectionEP.instantiateTool(InspectionEP.java:206)
	at com.intellij.codeInspection.ex.InspectionToolWrapper.getTool(InspectionToolWrapper.java:76)
	at com.intellij.codeInspection.ex.InspectionToolWrapper.getDisplayName(InspectionToolWrapper.java:151)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.addTool(InspectionProfileImpl.java:553)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.initialize(InspectionProfileImpl.java:474)
	at com.intellij.codeInspection.ex.NewInspectionProfile.initInspectionTools(InspectionProfile.kt:112)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.initialize(InspectionProfileImpl.java:461)
	at com.intellij.codeInspection.ex.NewInspectionProfile.initInspectionTools(InspectionProfile.kt:112)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.getToolsOrNull(InspectionProfileImpl.java:881)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.getInspectionTool(InspectionProfileImpl.java:295)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.getUnwrappedTool(InspectionProfileImpl.java:301)
	at com.intellij.xml.util.HtmlUtil.getEntitiesString(HtmlUtil.java:319)
	at com.intellij.xml.util.HtmlUtil.getCustomTagDescriptors(HtmlUtil.java:296)
	at org.intellij.html.RelaxedHtmlFromRngNSDescriptor.getRootElementsDescriptors(RelaxedHtmlFromRngNSDescriptor.java:74)
	at com.intellij.psi.impl.source.xml.XmlDocumentImpl.getNSDescriptorFromMetaData(XmlDocumentImpl.java:341)
	at com.intellij.psi.impl.source.xml.XmlDocumentImpl.getNsDescriptorFormDocType(XmlDocumentImpl.java:319)
	at com.intellij.psi.impl.source.xml.XmlDocumentImpl.getDefaultNSDescriptorInner(XmlDocumentImpl.java:198)
	at com.intellij.psi.impl.source.xml.XmlDocumentImpl.lambda$getDefaultNSDescriptor$0(XmlDocumentImpl.java:164)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:235)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:236)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.psi.impl.source.xml.XmlDocumentImpl.getDefaultNSDescriptor(XmlDocumentImpl.java:175)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getNSDescriptor(XmlTagDelegate.java:227)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getNSDescriptor(XmlTagImpl.java:100)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getNSDescriptor(XmlTagDelegate.java:230)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getNSDescriptor(XmlTagImpl.java:100)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getNSDescriptor(XmlTagDelegate.java:230)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getNSDescriptor(XmlTagImpl.java:100)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getNSDescriptor(XmlTagDelegate.java:230)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getNSDescriptor(XmlTagImpl.java:100)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getNSDescriptor(XmlTagDelegate.java:230)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getNSDescriptor(XmlTagImpl.java:100)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getNSDescriptor(XmlTagDelegate.java:230)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getNSDescriptor(XmlTagImpl.java:100)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getNSDescriptor(XmlTagDelegate.java:230)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getNSDescriptor(XmlTagImpl.java:100)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getNSDescriptor(XmlTagDelegate.java:230)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getNSDescriptor(XmlTagImpl.java:100)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getNSDescriptor(XmlTagDelegate.java:230)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getNSDescriptor(XmlTagImpl.java:100)
	at com.intellij.xml.util.XmlUtil.isTagDefinedByNamespace(XmlUtil.java:1235)
	at org.angularjs.codeInsight.tags.AngularJSTagDescriptorsProvider.getDescriptor(AngularJSTagDescriptorsProvider.java:60)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.computeElementDescriptor(XmlTagDelegate.java:457)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate$1.compute(XmlTagDelegate.java:436)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:153)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:235)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:236)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:76)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:150)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:120)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getDescriptor(XmlTagDelegate.java:432)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getDescriptor(XmlTagImpl.java:129)
	at com.intellij.xml.util.XmlEnumeratedValueReferenceProvider$1.getDescriptor(XmlEnumeratedValueReferenceProvider.java:93)
	at com.intellij.xml.util.XmlEnumeratedValueReferenceProvider$1.getDescriptor(XmlEnumeratedValueReferenceProvider.java:89)
	at com.intellij.xml.util.XmlEnumeratedValueReferenceProvider.getReferencesByElement(XmlEnumeratedValueReferenceProvider.java:63)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:204)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:167)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:146)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:44)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getReferencesImpl(XmlTagDelegate.java:161)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getDefaultReferences(XmlTagDelegate.java:127)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getReferences(XmlTagImpl.java:95)
	at com.intellij.psi.PsiReferenceServiceImpl.doGetReferences(PsiReferenceServiceImpl.java:35)
	at com.intellij.psi.PsiReferenceServiceImpl.getReferences(PsiReferenceServiceImpl.java:24)
	at com.intellij.psi.search.SingleTargetRequestResultProcessor.processTextOccurrence(SingleTargetRequestResultProcessor.java:32)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$5.lambda$execute$0(PsiSearchHelperImpl.java:948)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTreeUp(LowLevelSearchUtil.java:87)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.lambda$processElementsAtOffsets$0(LowLevelSearchUtil.java:178)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processOffsets(LowLevelSearchUtil.java:204)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsAtOffsets(LowLevelSearchUtil.java:177)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$5.execute(PsiSearchHelperImpl.java:944)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:280)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:271)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:25)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:885)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:25)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processCandidates$18(PsiSearchHelperImpl.java:905)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processVirtualFile$11(PsiSearchHelperImpl.java:543)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1132)
	at com.intellij.openapi.application.ex.ApplicationUtil.tryRunReadAction(ApplicationUtil.java:33)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processVirtualFile(PsiSearchHelperImpl.java:525)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processPsiFileRoots$7(PsiSearchHelperImpl.java:400)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processFilesConcurrentlyDespiteWriteActions$8(PsiSearchHelperImpl.java:473)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processFilesConcurrentlyDespiteWriteActions$9(PsiSearchHelperImpl.java:472)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class de.platon42.intellij.plugins.cajon.inspections.ImplicitAssertionInspection
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateExtensionWithPicoContainerOnlyIfNeeded(ComponentManagerImpl.kt:675)
	... 123 more

**Comment by chrisly42** [comment]
This seems to be related to https://intellij-support.jetbrains.com/hc/en-us/community/posts/360009768820-Plugin-build-fails-on-IJ-2020-2-3-EAP and https://intellij-support.jetbrains.com/hc/en-us/community/posts/360009740299-2020-3-EAP-Incompatible-with-JDK8-

I will try to recompile stuff with JDK 11 and provide an update ASAP. Thanks for letting me know! (Note: putting the stacktrace in an attachment would have been much better to read).

**Comment by chrisly42** [comment]
The ImplicitAssertionInspection accidentally had "doesNotHave" twice within a CallMatcher. And it seems as if the 2020.3 EAP version now checks that all added method call names are unique. That broke the plugin as a constant field of the class could not be initialized.

Thank you for your report. I will try to get a fixed version (1.11) ready by tomorrow (available on the release channel usually on Monday or Tuesday).

**Comment by chrisly42** [comment]
Should be resolved with Version 1.11 uploaded today.

**Comment by doublefx** [comment]
I just got the update yesterday and it seems to be ok, thanks and sorry for the stack trace.
